<a href="https://colab.research.google.com/github/abdinegara783/ML-Mentoring-Platform-Dicoding/blob/main/data_sentimen_feedback.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv("reviews_train.csv", error_bad_lines=False)
df.head()

<ipython-input-1-4e5a5e045dfc>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("reviews_train.csv", error_bad_lines=False)

                                                text sentiment
0  Now, I won't deny that when I purchased this o...  Negative
1  The saddest thing about this "tribute" is that...  Negative
2  Last night I decided to watch the prequel or s...  Negative
3  I have to admit that i liked the first half of...  Negative
4  I was not impressed about this film especially...  Negative

In [5]:
df['sentiment'].unique()

array(['Negative', 'Positive'], dtype=object)

In [3]:
df[df['sentiment']=='Positive']

                                                   text sentiment
5     The original movie, The Odd Couple, has some w...  Positive
6     This was a great movie with a good cast, all o...  Positive
8     Fast-paced, funny, sexy, and spectacular. Cagn...  Positive
16    A movie of outstanding brilliance and a poigna...  Positive
19    It appears even the director doesn't like this...  Positive
...                                                 ...       ...
7492  A stunning film of high quality.<br /><br />Ap...  Positive
7494  I'm amazed we see even one nay-sayer criticizi...  Positive
7496  Arthur is middle aged rich 'kid' who drinks li...  Positive
7497  A River Runs Through It is based on the true s...  Positive
7498  Holy crap this is so hysterical! Why aren't Am...  Positive

[3738 rows x 2 columns]